# This is a basic workflow to help you get started with Actions

name: MacOS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-11

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@1.0.8
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1
      - name: Prepare MacOS
        run: gem install cardano_wallet

      - name: Check docker-compose
        run: |
          wget https://raw.githubusercontent.com/input-output-hk/cardano-wallet/master/docker-compose.yml
          NETWORK=testnet docker-compose up -d
          ./scripts/connect_wallet.rb
