name: Docker-compose Windows
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1
      - name: Install cardano_wallet gem
        run: gem install cardano_wallet
      - name: Check docker-compose
        run: |
          wget https://raw.githubusercontent.com/input-output-hk/cardano-wallet/master/docker-compose.yml
          docker-compose up -d
          ./scripts/connect_wallet.rb
        env:
          NETWORK: testnet
